version: "3"

services:
  postgres:
    image: postgres:latest
    restart: always
    volumes:
      - postgres_db:/var/lib/postgresql/data
    env_file: .env

  moomin:
    build: .
    env_file: .env
    depends_on:
      - postgres
      - redis
    links:
      - postgres:postgres
      - redis:redis

    volumes:
      - ./:/app

  redis:
    image: redis:alpine
    restart: always

volumes:
  postgres_db:
